### ISSUE TITLE
Symbol after motd from placeholder

### ISSUE THREAD

**Issue by notariuss** [megamichiel/AnimatedMenu#8]
![image](https://user-images.githubusercontent.com/6098757/34303499-520c5150-e73e-11e7-892d-9d386c11cb79.png)
BedWars Rel cfg
```
bungeecord:
  enabled: true
  hubserver: lobby_bedwars
  endgame-in-lobby: true
  full-restart: true
  spigot-restart: true
  motds:
    running: |
      &7[&b$currentplayers$&7/&b$maxplayers$&7]
    stopped: |
      &c[Stopped]
    full: |
      &7[&b$currentplayers$&7/&b$maxplayers$&7]
```
AnimatedMenu cfg
```
  Lore:
    1:
    - '%animatedmenu_motd_bedwars1%'
```
